### ISSUE TITLE
Unable to build/run

### ISSUE THREAD

**Issue by Shidoengie** [scambier/tic80-typescript#12]
whenever i try to build by running tsc80 build or tsc80 run i always get this issue 

```
PS D:\tic80\test> tsc80 build
Compiling TypeScript...
'tsc' is not recognized as an internal or external command,
operable program or batch file.
node:child_process:926
    throw err;
    ^

Error: Command failed: tsc
'tsc' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (node:child_process:851:11)
    at Object.execSync (node:child_process:923:15)
    at compile (C:\Users\AEPBS\AppData\Roaming\npm\node_modules\tic80-typescript\bin\tsc80.js:120:23)
    at compileAndRun (C:\Users\AEPBS\AppData\Roaming\npm\node_modules\tic80-typescript\bin\tsc80.js:114:9)
    at build (C:\Users\AEPBS\AppData\Roaming\npm\node_modules\tic80-typescript\bin\tsc80.js:110:9)
    at Command.<anonymous> (C:\Users\AEPBS\AppData\Roaming\npm\node_modules\tic80-typescript\bin\tsc80.js:24:5)
    at Command.listener [as _actionHandler] (C:\Users\AEPBS\AppData\Roaming\npm\node_modules\tic80-typescript\node_modules\commander\index.js:922:31)
    at Command._parseCommand (C:\Users\AEPBS\AppData\Roaming\npm\node_modules\tic80-typescript\node_modules\commander\index.js:1503:14)
    at Command._dispatchSubcommand (C:\Users\AEPBS\AppData\Roaming\npm\node_modules\tic80-typescript\node_modules\commander\index.js:1443:18) {
  status: 1,
  signal: null,
  output: [
    null,
    "'tsc' is not recognized as an internal or external command,\r\n" +
      'operable program or batch file.\r\n'
  ],
  pid: 9132,
  stdout: '',
  stderr: "'tsc' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.\r\n'
}

Node.js v18.7.0
```
i dont know why this happens and i havent been able to fix it

**Comment by scambier** [comment]
Have you followed the [prerequisites](https://github.com/scambier/tic80-typescript#pre-requisites) in the readme? Looks like typescript isn't installed. If it is, open a new terminal instance (to make sure that everything is up-to-date) and check that `tsc` is available in your PATH.

**Comment by Shidoengie** [comment]
oh mb its working now
